// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/notebook.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Notebook struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Marca                string   `protobuf:"bytes,3,opt,name=marca,proto3" json:"marca,omitempty"`
	Modelo               string   `protobuf:"bytes,4,opt,name=modelo,proto3" json:"modelo,omitempty"`
	NumeroSerie          int64    `protobuf:"varint,5,opt,name=numeroSerie,proto3" json:"numeroSerie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notebook) Reset()         { *m = Notebook{} }
func (m *Notebook) String() string { return proto.CompactTextString(m) }
func (*Notebook) ProtoMessage()    {}
func (*Notebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_55e52f1fbaffee0b, []int{0}
}

func (m *Notebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notebook.Unmarshal(m, b)
}
func (m *Notebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notebook.Marshal(b, m, deterministic)
}
func (m *Notebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notebook.Merge(m, src)
}
func (m *Notebook) XXX_Size() int {
	return xxx_messageInfo_Notebook.Size(m)
}
func (m *Notebook) XXX_DiscardUnknown() {
	xxx_messageInfo_Notebook.DiscardUnknown(m)
}

var xxx_messageInfo_Notebook proto.InternalMessageInfo

func (m *Notebook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notebook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Notebook) GetMarca() string {
	if m != nil {
		return m.Marca
	}
	return ""
}

func (m *Notebook) GetModelo() string {
	if m != nil {
		return m.Modelo
	}
	return ""
}

func (m *Notebook) GetNumeroSerie() int64 {
	if m != nil {
		return m.NumeroSerie
	}
	return 0
}

type CreateNotebookRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Marca                string   `protobuf:"bytes,2,opt,name=marca,proto3" json:"marca,omitempty"`
	Modelo               string   `protobuf:"bytes,3,opt,name=modelo,proto3" json:"modelo,omitempty"`
	NumeroSerie          int64    `protobuf:"varint,4,opt,name=numeroSerie,proto3" json:"numeroSerie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNotebookRequest) Reset()         { *m = CreateNotebookRequest{} }
func (m *CreateNotebookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotebookRequest) ProtoMessage()    {}
func (*CreateNotebookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55e52f1fbaffee0b, []int{1}
}

func (m *CreateNotebookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotebookRequest.Unmarshal(m, b)
}
func (m *CreateNotebookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotebookRequest.Marshal(b, m, deterministic)
}
func (m *CreateNotebookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotebookRequest.Merge(m, src)
}
func (m *CreateNotebookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotebookRequest.Size(m)
}
func (m *CreateNotebookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotebookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotebookRequest proto.InternalMessageInfo

func (m *CreateNotebookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNotebookRequest) GetMarca() string {
	if m != nil {
		return m.Marca
	}
	return ""
}

func (m *CreateNotebookRequest) GetModelo() string {
	if m != nil {
		return m.Modelo
	}
	return ""
}

func (m *CreateNotebookRequest) GetNumeroSerie() int64 {
	if m != nil {
		return m.NumeroSerie
	}
	return 0
}

type CreateNotebookResponse struct {
	Notebook             *Notebook `protobuf:"bytes,1,opt,name=notebook,proto3" json:"notebook,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateNotebookResponse) Reset()         { *m = CreateNotebookResponse{} }
func (m *CreateNotebookResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNotebookResponse) ProtoMessage()    {}
func (*CreateNotebookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55e52f1fbaffee0b, []int{2}
}

func (m *CreateNotebookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotebookResponse.Unmarshal(m, b)
}
func (m *CreateNotebookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotebookResponse.Marshal(b, m, deterministic)
}
func (m *CreateNotebookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotebookResponse.Merge(m, src)
}
func (m *CreateNotebookResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNotebookResponse.Size(m)
}
func (m *CreateNotebookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotebookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotebookResponse proto.InternalMessageInfo

func (m *CreateNotebookResponse) GetNotebook() *Notebook {
	if m != nil {
		return m.Notebook
	}
	return nil
}

func init() {
	proto.RegisterType((*Notebook)(nil), "Notebook")
	proto.RegisterType((*CreateNotebookRequest)(nil), "CreateNotebookRequest")
	proto.RegisterType((*CreateNotebookResponse)(nil), "CreateNotebookResponse")
}

func init() { proto.RegisterFile("proto/notebook.proto", fileDescriptor_55e52f1fbaffee0b) }

var fileDescriptor_55e52f1fbaffee0b = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xed, 0x8f, 0x8d, 0xed, 0x0d, 0xaa, 0x3c, 0x66, 0x0d, 0x9e, 0x4a, 0x41, 0xd8, 0xa9,
	0x83, 0xf9, 0x07, 0x08, 0xee, 0xee, 0xa1, 0x03, 0x0f, 0x5e, 0xa4, 0x6b, 0x1f, 0x52, 0xb4, 0x79,
	0x31, 0xcd, 0xbc, 0x08, 0xfe, 0xed, 0xc2, 0x73, 0x2d, 0xfe, 0x08, 0x9e, 0x92, 0xef, 0x27, 0x21,
	0x9f, 0x6f, 0x12, 0x58, 0x1a, 0xcb, 0x8e, 0xd7, 0x9a, 0x1d, 0xed, 0x99, 0x9f, 0x0b, 0x89, 0xf9,
	0x07, 0xcc, 0xee, 0x8e, 0x04, 0x13, 0x08, 0xdb, 0x46, 0x05, 0x59, 0xb0, 0x9a, 0x97, 0x61, 0xdb,
	0x20, 0x42, 0xac, 0xab, 0x8e, 0x54, 0x28, 0x44, 0xe6, 0xb8, 0x84, 0x49, 0x57, 0xd9, 0xba, 0x52,
	0x91, 0xc0, 0xaf, 0x80, 0x29, 0x4c, 0x3b, 0x6e, 0xe8, 0x85, 0x55, 0x2c, 0xf8, 0x98, 0x30, 0x83,
	0x85, 0x3e, 0x74, 0x64, 0x79, 0x47, 0xb6, 0x25, 0x35, 0xc9, 0x82, 0x55, 0x54, 0x7e, 0x47, 0xf9,
	0x3b, 0x9c, 0x6f, 0x2d, 0x55, 0x8e, 0x86, 0x16, 0x25, 0xbd, 0x1e, 0xa8, 0x77, 0xa3, 0x3c, 0xf0,
	0xc9, 0x43, 0xbf, 0x3c, 0xfa, 0x4f, 0x1e, 0xff, 0x95, 0xdf, 0x40, 0xfa, 0x5b, 0xde, 0x1b, 0xd6,
	0x3d, 0xe1, 0x15, 0xcc, 0x86, 0x87, 0x92, 0x06, 0x8b, 0xcd, 0xbc, 0x18, 0x37, 0x8d, 0x4b, 0x9b,
	0x7b, 0x38, 0x1d, 0xe8, 0x8e, 0xec, 0x5b, 0x5b, 0x13, 0x6e, 0x21, 0xf9, 0x79, 0x26, 0xa6, 0x85,
	0xf7, 0x86, 0x97, 0x17, 0x85, 0x5f, 0x9e, 0x9f, 0xdc, 0x9e, 0x3d, 0x24, 0x86, 0xeb, 0xc7, 0x27,
	0x6b, 0xea, 0xb5, 0xfc, 0xd3, 0x7e, 0x2a, 0xc3, 0xf5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c,
	0x25, 0x04, 0x87, 0xc6, 0x01, 0x00, 0x00,
}
